[[dependencies]]
name = "anyhow"
version = "1"

[[dependencies]]
name = "async-trait"
version = "0.1"

[[dependencies]]
name = "axum"
version = "0.8"

[[dependencies]]
name = "base64"
version = "0.22"

[[dependencies]]
name = "bytes"
version = "1"

[[dependencies]]
name = "cfg-if"
version = "1"

[[dependencies]]
name = "chrono"
version = "0.4"

[[dependencies]]
name = "clap"
version = "4"

[[dependencies]]
name = "crossterm"
version = "0.29"

[[dependencies]]
name = "ctrlc"
version = "3"

[[dependencies]]
name = "derive_more"
version = "2"

[[dependencies]]
name = "env_logger"
version = "0.11"

[[dependencies]]
name = "flume"
version = "0.11"

[[dependencies]]
name = "futures"
version = "0.3"

[[dependencies]]
name = "interprocess"
version = "2"

[[dependencies]]
name = "libc"
version = "0.2"

[[dependencies]]
name = "log"
version = "0.4"

[[dependencies]]
name = "num_enum"
version = "0.7"

[[dependencies]]
name = "once_cell"
version = "1"

[[dependencies]]
name = "oneshot"
version = "0.1"

[[dependencies]]
name = "parking_lot"
version = "0.12"

[[dependencies]]
name = "percent-encoding"
version = "2"

[[dependencies]]
name = "postcard"
version = "1"

[[dependencies]]
name = "rand"
version = "0.9"

[[dependencies]]
name = "ratatui"
version = "0.29"

[[dependencies]]
name = "rmodbus"
version = "0.12"

[[dependencies]]
name = "rumqttc"
version = "0.25"

[[dependencies]]
name = "serde"
version = "1"

[[dependencies]]
name = "serde_json"
version = "1"

[[dependencies]]
name = "serde_json_path"
version = "0.7"

[[dependencies]]
name = "serialport"
version = "4"

[[dependencies]]
name = "sqids"
version = "0.4"

[[dependencies]]
name = "strum"
version = "0.27"

[[dependencies]]
name = "tokio"
version = "1"

[[dependencies]]
name = "toml"
version = "0.9"

[[dependencies]]
name = "tracing"
version = "0.1"

[[dependencies]]
name = "tracing-appender"
version = "0.2"

[[dependencies]]
name = "tracing-subscriber"
version = "0.3"

[[dependencies]]
name = "unicode-width"
version = "0.2"

[[dependencies]]
name = "ureq"
version = "3"

[[dependencies]]
name = "url"
version = "2"

[[dependencies]]
name = "uuid"
version = "1"

[[dependencies]]
name = "whoami"
version = "1"

[[dependencies]]
name = "yuuka"
version = "0.6"

[license_map]
anyhow = "MIT OR Apache-2.0"
async-trait = "MIT OR Apache-2.0"
axum = "MIT"
base64 = "MIT OR Apache-2.0"
bytes = "MIT"
cfg-if = "MIT OR Apache-2.0"
chrono = "MIT OR Apache-2.0"
clap = "MIT OR Apache-2.0"
crossterm = "MIT"
ctrlc = "MIT/Apache-2.0"
derive_more = "MIT"
env_logger = "MIT OR Apache-2.0"
flume = "Apache-2.0/MIT"
futures = "MIT OR Apache-2.0"
interprocess = "MIT OR Apache-2.0"
libc = "MIT OR Apache-2.0"
log = "MIT OR Apache-2.0"
num_enum = "BSD-3-Clause OR MIT OR Apache-2.0"
once_cell = "MIT OR Apache-2.0"
oneshot = "MIT OR Apache-2.0"
parking_lot = "MIT OR Apache-2.0"
percent-encoding = "MIT OR Apache-2.0"
postcard = "MIT OR Apache-2.0"
rand = "MIT OR Apache-2.0"
ratatui = "MIT"
rmodbus = "Apache-2.0"
rumqttc = "Apache-2.0"
serde = "MIT OR Apache-2.0"
serde_json = "MIT OR Apache-2.0"
serde_json_path = "MIT"
serialport = "MPL-2.0"
sqids = "MIT"
strum = "MIT"
tokio = "MIT"
toml = "MIT OR Apache-2.0"
tracing = "MIT"
tracing-appender = "MIT"
tracing-subscriber = "MIT"
unicode-width = "MIT OR Apache-2.0"
ureq = "MIT OR Apache-2.0"
url = "MIT OR Apache-2.0"
uuid = "Apache-2.0 OR MIT"
whoami = "Apache-2.0 OR BSL-1.0 OR MIT"
yuuka = "Apache-2.0"

[package]
authors = ["langyo <langyo.china@gmail.com>"]
license = "Apache-2.0"
name = "aoba"
repository = "https://github.com/celestia-island/aoba"
version = "0.0.9"
