[package]
name = "api_master"
version = "0.1.0"
edition = "2021"

[dependencies]
_main = { path = "../..", package = "aoba" }
anyhow = "1.0"
env_logger = "0.11"
log = "0.4"
tokio = { version = "1.0", features = ["full"] }
