[package]
name = "aoba_core"
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
parking_lot.workspace = true

chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
postcard.workspace = true

log.workspace = true

flume.workspace = true
tokio.workspace = true

serialport.workspace = true
interprocess.workspace = true

aoba_cli = { path = "../cli" }
aoba_protocol = { path = "../protocol" }

[dev-dependencies]
tokio-test.workspace = true
