[package]
name = "aoba_utils"
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
once_cell.workspace = true

serde.workspace = true
serde_json.workspace = true
postcard.workspace = true
toml.workspace = true
yuuka.workspace = true

log.workspace = true

tokio = { workspace = true, features = ["io-util", "net", "time"] }
interprocess = { version = "^2", features = ["tokio"] }

whoami.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
