name: Publish crates.io
on:
  push:
    tags: [v*]

jobs:
  basic_checks:
    name: Basic Checks
    uses: ./.github/workflows/basic-checks.yml

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: [basic_checks]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-release

      - run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - run: |-
          cargo release \
            publish \
            --all-features \
            --allow-branch HEAD \
            --no-confirm \
            --no-verify \
            --execute
